jobs:
  accessibility_alt_text_bot:
    if: ${{ github.event.issue || github.event.pull_request || github.event.discussion }}
    name: Check alt text is set on issue or pull requests
    runs-on: ubuntu-latest
    steps:
      - name: Get action 'github/accessibility-alt-text-bot'
        uses: github/accessibility-alt-text-bot@v1.4.0
name: Accessibility-alt-text-bot

on:
  discussion:
    types: [created, edited]
  discussion_comment:
    types: [created, edited]

  issue_comment:
    types: [created, edited]
  issues:
    types: [edited, opened]
  pull_request:
    types: [edited, opened]
permissions:
  discussions: write
  issues: write
  pull-requests: write
