jobs:
  accessibility_alt_text_bot:
    if: ${{ github.event.issue || github.event.pull_request }}
    runs-on: ubuntu-latest
    steps:
      - uses: github/accessibility-alt-text-bot@v1.4.0

name: Accessibility Alt Text Bot

on:
  issue:
    types:
      - created
      - edited
  issue_comment:
    types:
      - created
      - edited
  pull_request:
    types:
      - created
      - edited

permissions:
  issues: write
  pull-requests: write
